### ISSUE TITLE
How can I test in my own .mat files?

### ISSUE THREAD

**Issue by surajitsaikia27** [twtygqyy/pytorch-SRResNet#10]
I have converted my images to .mat files, later I realised that my files are not same as the testsets provided in the repository. Did anybody faced similar situation as mine?

**Comment by twtygqyy** [comment]
@surajitsaikia27 Please refer to the matlab code [here](https://github.com/twtygqyy/pytorch-LapSRN/blob/master/Test/generate_test_mat.m)

**Comment by surajitsaikia27** [comment]
thanks..I have successfully implemented  :D

**Comment by huchi00057** [comment]
> @surajitsaikia27請參考[此處的matlab代碼](https://github.com/twtygqyy/pytorch-LapSRN/blob/master/Test/generate_test_mat.m)

how to run this code? 😊
