### ISSUE TITLE
Problem in 3-channeled image output

### ISSUE THREAD

**Issue by sonal-bansal** [twtygqyy/pytorch-SRResNet#21]
Hi,
When i'm displaying my 3 channeled output image, it is not at all good and looks something like this:-
![rgb](https://user-images.githubusercontent.com/33753404/52058759-24883200-258e-11e9-9922-fb5622a198d3.png)

When I'm displaying my single channeled output ,it still shows proper image features ,like this:-
![singlechannel](https://user-images.githubusercontent.com/33753404/52058837-4e415900-258e-11e9-8d9c-7df1960a154e.png)

Though I've started to train my model and it isn't even 50 epochs till now, but I really want to know why is this happening.

Thank you .

**Comment by twtygqyy** [comment]
Hi @sonal-bansal, check the type of the array and make sure it is np.uint8 before imshow

**Comment by sonal-bansal** [comment]
Yeah,I got it . How much did you trained your srresnet?

Thanks.
